### ISSUE TITLE
Not Proper Documentation

### ISSUE THREAD

**Issue by rishi11** [mit09/CS5610-mit09#5]
There is no proper documentation of experiments. Code snippet is missing in experiments.

**Comment by mit09** [comment]
i have added code snippets for Week 4 experiments

**Comment by rishi11** [comment]
Hi mit09,

This issue is for all the experiments. When you believe that you are done with documentation for  all your experiments, close the issue.

**Comment by mit09** [comment]
Added documentation that was missing from week 1 to 4
